### ISSUE TITLE
A couple of suggestions to improve the documentation

### ISSUE THREAD

**Issue by dutty5** [pschichtel/postfix-rest-connector#9]
Hi, thank you for this wonderful piece of software. We already started using it to operate our corporate mx servers in a centralized and manageable manner.

I have a few suggestions regarding the project.

While I understand that those who will need this software are probably quite competent admins, still you will save some their valuable time if:

- if you release the jar. There is an unnecessary overhead to run docker on a server, especially if there is no docker originally installed. I compiled your source code into jar file, and it runs just fine with java 21 directly (which is already present on the server). Just created unprivileged user and systemd service to handle start/stop/restart, and I'm good to go.
- if you include some hints in the README how to run properly the docker package provided. While `$ docker run [package.name] /etc/postfix/rest-connector.json` may be sufficient and almost obvious, still it takes time to try and error. And nobody knows if any other command line options for docker are necessary or not. 
- if you include in the README more details about the location and use of the config file. The hint `Usage: <config file>` is a bit ambiguous.

Overall, I found that the README file covers the API well, but is completely silent on the installation and running procedures. Some elaboration on this will be helpful.

Cheers

**Comment by pschichtel** [comment]
Yeah completely valid. I wrote the documentation entirely around my use-case and as the author I obviously know how to run it :D

I'll have a look some time this week, I might also do some updates while I'm at it.

**Comment by pschichtel** [comment]
I've made a release with binaries attached: https://github.com/pschichtel/postfix-rest-connector/releases/tag/postfix-rest-connector-3.0.0

Also I added a small section to the readme and an example docker-compose.yml. I don't really see the point of walking people through how to use docker (or podman, or kubernetes, ...) and its million ways of using it depending on their use-case.

There is container images for the java version and the native versions and there is binaries for linux/amd64, linux/arm64 and windows/amd64 and there is also a fat-jar that can run on Java 11+ without additional dependencies, people should figure out how to best integrate any of these options into their infrastructure.

**Comment by dutty5** [comment]
What is done with regard to binaries is much more than we had anticipated) Great work! Thank you

**Comment by pschichtel** [comment]
I originally wanted to go native, but kotlin MP lacked some things I needed. These are now available, so I did the switch. Took a little longer than anticipated, but worked out great.

**Comment by dutty5** [comment]
Hi, yesterday I tried to replace my own previously compiled jar with your binary (amd64), and it seems the binary has some problem. I had to revert to my own build.

On one of the machines (EL8) the binary did not want to start with 0.0.0.0:9001 bind address, throwing the error 'posix.error, address already in use'. Address was not in use, restart of the machine did not help, and I changed to 127.0.0.1:9001, and this worked.

On another machine with the identical OS and configuration but hypervisor the bind address 0.0.0.0 worked without this error.

Another, more serious problem it that with your binary the postfix seems to be unable to talk to our API backend. All messages are rejected with the sending smtp server receiving the error message from our smtpd 'write queue error'. I switched back to my own jar, and it started to work again.

**Comment by dutty5** [comment]
I did not try your jar.

**Comment by dutty5** [comment]
I checked the access logs of the backend and it shows nothing, there were no requests from the postfix-rest-connector. So, looks like the connector does listen on the configured ports but no further requests are made to the backend.

**Comment by dutty5** [comment]
I also wanted to mention that example configuration in the README:
`tcp:localhost:9001` has a weird problem with resolving the `localhost` by `postfix cleanup` process.
It should be `tcp:127.0.0.1:9001` to avoid the problem with `cleanup`.

**Comment by dutty5** [comment]
Not very informative, just to be precise:
```
Out: 451 4.3.0 Error: queue file write error
In:  RSET
Out: 421 4.3.0 Mail system error
```
This is how postfix replies to a sending party while been unable to access the lookup tables supposed to be provided by the rest-connector.

**Comment by pschichtel** [comment]
> I also wanted to mention that example configuration in the README: `tcp:localhost:9001` has a weird problem with resolving the `localhost` by `postfix cleanup` process. It should be `tcp:127.0.0.1:9001` to avoid the problem with `cleanup`.

I changed that. postfix might not see the /etc/hosts due to some processes running in a chroot environment.

**Comment by pschichtel** [comment]
it would be very helpful if you can try this. my tests all passed, both for the java version and the native version, but some of these suggest that there might be native-specific issues that might not occur in the java version. I'll setup some more tests to reproduce this.

**Comment by dutty5** [comment]
Yes sure, later today I'll check with jar

**Comment by dutty5** [comment]
Hi, your released jar works. Tested right now with JDK 21. 

To sum up: the jar works as expected without any modification of the config. The Binary doesn't work. The binary starts normally, listens to the configured ports, but no requests go to the backend. Platform is
```
This system is running Oracle Linux Server release 8.10
Kernel is 5.15.0-301.163.5.2.el8uek.x86_64
```
The config is simple:
```
{
  "user-agent": "Postfix REST Connector",
  "endpoints": [
    {
      "name": "domain-lookup",
      "mode": "tcp-lookup",
      "target": "https://......",
      "bind-address": "127.0.0.1",
      "bind-port": 9001,
      "auth-token": "...",
      "request-timeout": 1500
    },
    {
      "name": "virtual-lookup",
      "mode": "tcp-lookup",
      "target": "https://...",
      "bind-address": "127.0.0.1",
      "bind-port": 9002,
      "auth-token": "...",
      "request-timeout": 1500
    }
  ]
}
```
Postfix:

```
virtual_alias_domains = tcp:127.0.0.1:9001
virtual_alias_maps = tcp:127.0.0.1:9002
```

Since the binary probably doesn't write any log (cannot see anything related) it's difficult to know what's wrong with it.

**Comment by dutty5** [comment]
Hi, could you reproduce the issue with the native binary? Or, confirmed they do work normally, and then I need to dig into our system configuration?

**Comment by pschichtel** [comment]
I didn't have the time yet to give this the proper look it needs, since I might have to debug the low-level libraries I depend on.

> Since the binary probably doesn't write any log (cannot see anything related) it's difficult to know what's wrong with it.

actually the native binary should be logging the same things (with a slightly different format) as the JVM version. Would it be possible to run the binary with `strace` and provide me the output?

**Comment by pschichtel** [comment]
> On one of the machines (EL8) the binary did not want to start with 0.0.0.0:9001 bind address, throwing the error 'posix.error, address already in use'. Address was not in use, restart of the machine did not help, and I changed to 127.0.0.1:9001, and this worked.

I've not been able to reproduce this and I haven't seen a reason why that would be the case. Since 0.0.0.0 tries to bind all interfaces, is it possible that the port was bound on any of the interfaces?

> Another, more serious problem it that with your binary the postfix seems to be unable to talk to our API backend. All messages are rejected with the sending smtp server receiving the error message from our smtpd 'write queue error'

that in combination with 

> Since the binary probably doesn't write any log (cannot see anything related) it's difficult to know what's wrong with it.

suggests that the server did not properly start up and somehow got stuck before logging anything. seeing the output of strace could help, alternatively a stacktrace using gdb when it is stuck.

**Comment by dutty5** [comment]
Hello, I finally found some time to debug the issue with the native binary.

Below is the log how it runs on Centos 7. I hope this helps.

<details>
<summary>
crash log
</summary>

```
INFO: [] Client InetSocketAddress(127.0.0.1:39062) connected to InetSocketAddress(0.0.0.0:9003) (endpoint: transport-lookup)
INFO: [] [redacted for privacy] - tcp-lookup request on endpoint transport-lookup: get *
INFO: [] [redacted for privacy] - connector endpoint request:
GET https://[redacted for privacy]/[redacted for privacy]?key=%2A
X-Auth-Token: [redacted for privacy]
X-Request-Id: [redacted for privacy]


Uncaught Kotlin exception: kotlin.IllegalStateException: TLS sessions are not supported on Native platform.
ERROR: [] Client socket io.ktor.network.sockets.TCPSocketNative@aa67e028 closed due to error while processing!, Caused by: 'TLS sessions are not supported on Native platform.'
    at 0   postfix-rest-connector-3.0.0-amd64  0x5b41b9           kfun:io.ktor.network.tls.$tlsCOROUTINE$0.invokeSuspend#internal + 521 
    at 1   postfix-rest-connector-3.0.0-amd64  0x5babec           kfun:io.ktor.client.engine.cio.Endpoint.$connectCOROUTINE$5.invokeSuspend#internal + 4220 
    at 2   postfix-rest-connector-3.0.0-amd64  0x4202ce           kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} + 206 
    at 3   postfix-rest-connector-3.0.0-amd64  0x4dd72b           kfun:kotlinx.coroutines.internal.ScopeCoroutine#afterResume(kotlin.Any?){} + 155 
    at 4   postfix-rest-connector-3.0.0-amd64  0x4aed50           kfun:kotlinx.coroutines.AbstractCoroutine#resumeWith(kotlin.Result<1:0>){} + 160 
    at 5   postfix-rest-connector-3.0.0-amd64  0x4203d9           kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} + 473 
    at 6   postfix-rest-connector-3.0.0-amd64  0x4da12f           kfun:kotlinx.coroutines.DispatchedTask#run(){} + 623 
    at 7   postfix-rest-connector-3.0.0-amd64  0x4db603           kfun:kotlinx.coroutines.internal.LimitedDispatcher.Worker.run#internal + 179 
    at 8   postfix-rest-connector-3.0.0-amd64  0x4e9e9c           kfun:kotlinx.coroutines.MultiWorkerDispatcher.$workerRunLoop$lambda$2COROUTINE$0.invokeSuspend#internal + 1692 
    at 9   postfix-rest-connector-3.0.0-amd64  0x4202ce           kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} + 206 
    at 10  postfix-rest-connector-3.0.0-amd64  0x4da12f           kfun:kotlinx.coroutines.DispatchedTask#run(){} + 623 
    at 11  postfix-rest-connector-3.0.0-amd64  0x4ba478           kfun:kotlinx.coroutines.EventLoopImplBase#processNextEvent(){}kotlin.Long + 808 
    at 12  postfix-rest-connector-3.0.0-amd64  0x4e38fb           kfun:kotlinx.coroutines#runBlocking(kotlin.coroutines.CoroutineContext;kotlin.coroutines.SuspendFunction1<kotlinx.coroutines.CoroutineScope,0:0>){0§<kotlin.Any?>}0:0 + 1691 
    at 13  postfix-rest-connector-3.0.0-amd64  0x4ea68a           kfun:kotlinx.coroutines.MultiWorkerDispatcher.$<init>$lambda$1$lambda$0$FUNCTION_REFERENCE$5.$<bridge-DNN>invoke(){}#internal + 282 
    at 14  postfix-rest-connector-3.0.0-amd64  0x631bdf           _ZN6Worker19processQueueElementEb + 1359 
    at 15  postfix-rest-connector-3.0.0-amd64  0x63160c           _ZN12_GLOBAL__N_113workerRoutineEPv + 92 
    at 16  libpthread.so.0                     0x7f90cf798ea4     0x0 + 140259932868260 
    at 17  libc.so.6                           0x7f90cea65b0c     clone + 108 
    Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cc3a3cc8, Dispatchers.IO]
        at 0   postfix-rest-connector-3.0.0-amd64  0x4d8f1e           kfun:kotlinx.coroutines.internal#handleUncaughtCoroutineException(kotlin.coroutines.CoroutineContext;kotlin.Throwable){} + 766 
        at 1   postfix-rest-connector-3.0.0-amd64  0x4b6ea4           kfun:kotlinx.coroutines#handleCoroutineException(kotlin.coroutines.CoroutineContext;kotlin.Throwable){} + 228 
        at 2   postfix-rest-connector-3.0.0-amd64  0x4afe21           kfun:kotlinx.coroutines.StandaloneCoroutine.handleJobException#internal + 33 
        at 3   postfix-rest-connector-3.0.0-amd64  0x4bd2de           kfun:kotlinx.coroutines.JobSupport.finalizeFinishingState#internal + 2462 
        at 4   postfix-rest-connector-3.0.0-amd64  0x4c18de           kfun:kotlinx.coroutines.JobSupport.tryMakeCompleting#internal + 1230 
        at 5   postfix-rest-connector-3.0.0-amd64  0x4c11b2           kfun:kotlinx.coroutines.JobSupport#makeCompletingOnce(kotlin.Any?){}kotlin.Any? + 226 
        at 6   postfix-rest-connector-3.0.0-amd64  0x4aed30           kfun:kotlinx.coroutines.AbstractCoroutine#resumeWith(kotlin.Result<1:0>){} + 128 
        at 7   postfix-rest-connector-3.0.0-amd64  0x4203d9           kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} + 473 
        at 8   postfix-rest-connector-3.0.0-amd64  0x4da054           kfun:kotlinx.coroutines.DispatchedTask#run(){} + 404 
```
</details>

**Comment by pschichtel** [comment]
ohhh, ok. So it seems that the ktor client engine that I used in the native builds, does not support TLS. I've never actually tested requests to https endpoints, because my use-cases have post-rest-connector and the target application within a shared isolated network, so TLS was never necessary.

If been considering rewriting this thing in rust, this is one more reason to do that. For now you'll have to stick to the java version. I'll add a note to the README.

**Comment by pschichtel** [comment]
For reference: https://youtrack.jetbrains.com/issue/KTOR-7262/CIO-client-TLS-session-support-for-native-targets

**Comment by dutty5** [comment]
There might be a workaround to use the stunnel.

**Comment by pschichtel** [comment]
the http client is generally configured to use keep alive connections, combined with session resumption on the server side, connection overhead usually isn't a huge concern.

If you have a setup with stunnel feel free to share it, I can add that to the documentation here.

**Comment by pschichtel** [comment]
@dutty5 I've just released 3.1, this version uses libcurl instead of ktor's limited CIO client. This version should not have issues connecting using TLS: https://github.com/pschichtel/postfix-rest-connector/releases/tag/postfix-rest-connector-3.1.0

**Comment by dutty5** [comment]
Hi, thanks for your effort.

I've checked the amd64 binary on Oracle Linux 8.10. There is some problem with the curl version or something. The crash log follows.

<details>
<summary>crash log</summary>

```
/usr/local/bin/postfix-rest-connector-3.1.0-amd64: /lib64/libcurl.so.4: no version information available (required by /usr/local/bin/postfix-rest-connector-3.1.0-amd64)
INFO: [Session] Bound endpoint domain-lookup to address: InetSocketAddress(0.0.0.0:9001)
INFO: [Session] Bound endpoint virtual-lookup to address: InetSocketAddress(0.0.0.0:9002)
INFO: [Session] Client InetSocketAddress(127.0.0.1:47356) connected to InetSocketAddress(0.0.0.0:9001) (endpoint: domain-lookup)
INFO: [TcpLookupHandler] [redacted] - tcp-lookup request on endpoint domain-lookup: get mta.platform-s.com
INFO: [TcpLookupHandler] [redacted] - connector endpoint request:
GET https://[redacted]/[redacted]?key=[redacted].com
X-Auth-Token: [redacted]
X-Request-Id: [redacted]


/usr/local/bin/postfix-rest-connector-3.1.0-amd64: symbol lookup error: /usr/local/bin/postfix-rest-connector-3.1.0-amd64: undefined symbol: curl_multi_wakeup, version CURL_OPENSSL_4
```
</details>

<details>
<summary>libcurl</summary>
[root@[redacted] ~]# ls -la /lib64/libcurl.so.4

lrwxrwxrwx 1 root root 16 Aug 21 01:29 /lib64/libcurl.so.4 -> libcurl.so.4.5.0
[root@[redacted] ~]# ls -la /lib64/libcurl.so.4.5.0
-rwxr-xr-x 1 root root 596536 Aug 21 01:30 /lib64/libcurl.so.4.5.0
</details>

**Comment by pschichtel** [comment]
*sigh* I originally wanted to statically link this, I guess I have to look more into that. Maybe the story ends here... kotlin/native's support for non-mobile platforms is kinda lacking. If this is not viable currently I'll be dropping the binary pre-builds for now. I think if you build the project on the target system, then it would link to the correct version.

**Comment by dutty5** [comment]
I see. Does your jar 3.1 build require externally linked curl library, or it relies on java in the same way as previous 3.0 build?

**Comment by dutty5** [comment]
By the way, a statically linked library is not always bad, this is not an unseen method, as long as the new build is released on a more or less scheduled manner to utilize any recent development and/or bug fixes.

**Comment by pschichtel** [comment]
> I see. Does your jar 3.1 build require externally linked curl library, or it relies on java in the same way as previous 3.0 build?

nothing changed regarding the java version, that's using java's built-in client.

> a statically linked library is not always bad, this is not an unseen method

yes, sadly I don't think it's a well supported use-case in kotlin/native currently.

**Comment by pschichtel** [comment]
yeah, static linking is not going to happen with kotlin/native anytime soon. I'll rather rewrite this in rust.
